### PR TITLE
Sequence a subdir instead of the whole entriesDir.

### PR DESCRIPTION
**Pull request by jiggoha**
This is what the config would look like if we implemented the idea of sequencing only a subdir under entriesDir instead of the entire entriesDir. It's the 2nd idea in this comment: https://github.com/transparency-dev/armored-witness-applet/pull/186#discussion_r1440300976.

I did some testing and it turns out we don't need to tweak the code in serverless-log after all.

The benefit to this PR is that we have guarantee that there will be no collisions across triggers. They all work (and clean up) in their own subdirectory under `entriesDir`.

### CODE REVIEW

**Comment by mhutchinson** [comment]
Let's evaluate the pros/cons of this when we meet tomorrow.

**Comment by AlCutter** [comment]
FWIW, the original "CLI" implementation handles this by having the `sequence` command take a glob of entries to sequence: https://github.com/transparency-dev/serverless-log/blob/main/cmd/sequence/main.go#L39

**Comment by jiggoha** [comment]
Following up from our ArmoredChatter this afternoon, I updated the description to include why we want to do this. My latest commit mitigates the formatting con a bit.

**Comment by jiggoha** [comment]
The applet-presubmit Cloud Build is failing right now. https://github.com/transparency-dev/armored-witness-applet/pull/199 should fix it.

**Comment by jiggoha** [comment]
> The applet-presubmit Cloud Build is failing right now. #199 should fix it.

The presubmit is now fixed and all checks are passing.

**Review by mhutchinson — APPROVED** [review]

**Pull request merged**
