### PR TITLE
Use h/w key derivation for witness key

### PR DESCRIPTION
**Pull request by AlCutter**
This is not quite as straightforward as it might be because the h/w doesn't support the Ed25519 keys directly, instead I'm using the AES key it does support as a secure prng to seed HKDF which I steal a few bytes from for generating the friendly name, and then pass through to note's keygen func.

@smeiklej Does this look legit?

### CODE REVIEW

**Review by abarisani — COMMENTED** [review]
This looks fine, be advised that when we will move to the CAAM we will generate a 32 bytes unique key (https://github.com/transparency-dev/armored-witness-os/blob/64b26af978d07c1daa87606f93e33cb5ab0e32f2/trusted_os/rpc.go#L165).

**Comment by smeiklej** [comment]
This does not look legit at all :).  Pseudorandom generators can only expand randomness, meaning if you start with a k-bit random string they can output a random string of length p(k) for some polynomial p.  If, as you're doing here, you start from a low-entropy seed (the current static string, but even the future proposed counter), it's easy for an attacker to guess keys, or even for witnesses to accidentally share keys and identities.

To be secure you'll need some source of entropy to get a (truly) random seed.  Things like the current time also don't work (too easy to guess), so hopefully there is some boot-time process that you can rely on to siphon off some random bits.

**Comment by abarisani** [comment]
> Thanks Sarah!
> 
> > This does not look legit at all :). Pseudorandom generators can only expand randomness, meaning if you start with a k-bit random string they can output a random string of length p(k) for some polynomial p. If, as you're doing here, you start from a low-entropy seed (the current static string, but even the future proposed counter), it's easy for an attacker to guess keys, or even for witnesses to accidentally share keys and identities.
> 
> I would have though it should be hard for witnesses to accidentally share/guess keys - during the call to `RPC.DeriveKey`) the seed string is (I believe - @abarisani?) encrypted with the hardware's secret key which is unique per device.
> 
> Or are you saying that this is still produces an insufficient amount of entropy for the expansion?
> 
> > To be secure you'll need some source of entropy to get a (truly) random seed. Things like the current time also don't work (too easy to guess), so hopefully there is some boot-time process that you can rely on to siphon off some random bits.

The runtime randomness is provided by a TRNG (w/ [CAAM](https://github.com/usbarmory/tamago/blob/master/soc/nxp/caam/rng.go#L56), w/ [RNGB](https://github.com/usbarmory/tamago/blob/d64a26341d560ecba4a745dcee44076d7cf2cd7a/soc/nxp/rngb/rngb.go#L121)).

The key derivation is defined [here](https://github.com/usbarmory/tamago/blob/d64a26341d560ecba4a745dcee44076d7cf2cd7a/soc/nxp/caam/key.go#L68) and I think Al is mentioning that he his using a predictable rng (per device given that it's seeded with the device random + unique key) solely for the purpose of attestation key derivation.

**Comment by smeiklej** [comment]
Ah okay, this makes a lot more sense.  I still don't think it's a good idea though to use this custom blend of SHA256 and AES.  Really you should be using only standardized methods for deterministic RNG, as outlined at https://csrc.nist.gov/publications/detail/sp/800-90a/rev-1/final.  This means you could use CTR-DRBG with AES or Hash-DRBG or HMAC-DRBG with SHA256.  I'm not an expert in this space but believe that all these protocols come with a proof of security (with perhaps CTR-DRBG coming with the most caveats, from a quick skim of the literature).

**Comment by abarisani** [comment]
> Ah okay, this makes a lot more sense. I still don't think it's a good idea though to use this custom blend of SHA256 and AES. Really you should be using only standardized methods for deterministic RNG, as outlined at https://csrc.nist.gov/publications/detail/sp/800-90a/rev-1/final. This means you could use CTR-DRBG with AES or Hash-DRBG or HMAC-DRBG with SHA256. I'm not an expert in this space but believe that all these protocols come with a proof of security (with perhaps CTR-DRBG coming with the most caveats, from a quick skim of the literature).

We are not blending SHA256, the RNG is purely the output of AES with internal key and a diversifier, the reason for not implementing a different scheme is that we either cannot access the unique key (DCP, where it remains internal and can only be used for AES) or we wouldn't want to extract it to external RAM.

When using CAAM we will be able to have full memory encryption and that is where different schemes can be supported.

**Comment by abarisani** [comment]
@AlCutter when CAAM is in place I'd suggest using the output of [caam.DeriveKey](https://github.com/usbarmory/tamago/blob/d64a26341d560ecba4a745dcee44076d7cf2cd7a/soc/nxp/caam/key.go#L68) with https://pkg.go.dev/github.com/canonical/go-sp800.90a-drbg (what do you think @smeiklej ?)

**Comment by smeiklej** [comment]
Yes, using a canonical implementation is even better!

**Comment by AlCutter** [comment]
Excellent, thanks both!

Ok, I'll park this PR until we get the rev2 boards with i.MX6UL and have the CAAM available, then I'll update.

**Comment by abarisani** [comment]
> > Ah okay, this makes a lot more sense. I still don't think it's a good idea though to use this custom blend of SHA256 and AES. Really you should be using only standardized methods for deterministic RNG, as outlined at https://csrc.nist.gov/publications/detail/sp/800-90a/rev-1/final. This means you could use CTR-DRBG with AES or Hash-DRBG or HMAC-DRBG with SHA256. I'm not an expert in this space but believe that all these protocols come with a proof of security (with perhaps CTR-DRBG coming with the most caveats, from a quick skim of the literature).
> 
> 
> 
> We are not blending SHA256, the RNG is purely the output of AES with internal key and a diversifier, the reason for not implementing a different scheme is that we either cannot access the unique key (DCP, where it remains internal and can only be used for AES) or we wouldn't want to extract it to external RAM.
> 
> 
> 
> When using CAAM we will be able to have full memory encryption and that is where different schemes can be supported.

To correct my comment, the unique key derived with AES is fed to HKDF, used as DRGB for ECC key generation, this is the code I originally suggested to @AlCutter taken for our GoKey project:

```
// DeviceKey derives a device key, uniquely and deterministically generated for
// this SoC for attestation purposes.
func DeviceKey() (deviceKey *ecdsa.PrivateKey, err error) {
	iv := make([]byte, aes.BlockSize)
	key, err := imx6ul.DCP.DeriveKey([]byte(diversifierDev), iv, -1)

	if err != nil {
		return
	}

	salt := imx6ul.UniqueID()
	r := hkdf.New(sha256.New, key, salt[:], nil)

	return keygen.ECDSALegacy(elliptic.P256(), r)
}
```

@smeiklej in case we don't want to import canonical packages this still uses a standard expansion function as DRGB, does this look fine to you?

**Comment by AlCutter** [comment]
We have the new rev2 boards now, so it would be good to get this PR moving again.
I've tidied it up a bit in the meantime.

@smeiklej @abarisani

**Comment by AlCutter** [comment]
@smeiklej ping :)

**Review by smeiklej — APPROVED** [review]
This looks much better to me (to the best of my ability to read the code!).

If this is going to be a Google launch one day, it's probably worth asking ISE Crypto for their opinion as well?

**Comment by AlCutter** [comment]
> If this is going to be a Google launch one day, it's probably worth asking ISE Crypto for their opinion as well?

Yup, good call - I've mentioned it to @meder.

I'm going to merge this as-is for now since it enables us to get on with other work this blocked, but it should be relatively easy to adapt to any changes to the key derivation coming from ISE.

**Pull request merged**
