### PR TITLE
Create scorecard.yml

### PR DESCRIPTION
**Pull request by AlCutter**

### CODE REVIEW

**Comment by phbnf** [comment]
All the other scorecard configs of our repos are called "scorecardS.yml", consistency on this sounds like a good idea?

**Comment by AlCutter** [comment]
> All the other scorecard configs of our repos are called "scorecardS.yml", consistency on this sounds like a good idea?

Sure, although this file was created automatically with the button on the workflow, so perhaps that changed at some point.

Either way, I'll update the other repos since `scorecard.yml` now seems to be the "recommended" name for the file.

**Comment by AlCutter** [comment]
> > All the other scorecard configs of our repos are called "scorecardS.yml", consistency on this sounds like a good idea?
> 
> Sure, although this file was created automatically with the button on the workflow, so perhaps that changed at some point.
> 
> Either way, I'll update the other repos since `scorecard.yml` now seems to be the "recommended" name for the file.

Ah, yes - even the content of the autogenerated file has switched from referencing "Scorecards" to "Scorecard" at some point between my creating the configs in Trillian etc. and here.

**Comment by roger2hk** [comment]
The workflow file in scorecard repo is named as `scorecard-analysis.yml`.

https://github.com/ossf/scorecard/blob/main/.github/workflows/scorecard-analysis.yml

**Comment by AlCutter** [comment]
> The workflow file in scorecard repo is named as `scorecard-analysis.yml`.
> 
> https://github.com/ossf/scorecard/blob/main/.github/workflows/scorecard-analysis.yml

Hehe, it's not consistent with what the autogen tool creates either :)
I don't think it really matters a huge deal, but having them called the same thing across all of _our_ repos seems reasonable.

**Comment by AlCutter** [comment]
https://github.com/google/trillian/pull/2986
https://github.com/google/certificate-transparency-go/pull/1068
https://github.com/transparency-dev/merkle/pull/58
https://github.com/transparency-dev/formats/pull/26
https://github.com/transparency-dev/witness/pull/42

(t-e doesn't have SC configured at the moment)

**Comment by phbnf** [comment]
+1

**Review by phbnf — APPROVED** [review]

**Pull request merged**
